export const Role = {
  PLATFORM_SUPER_ADMIN: 'PLATFORM_SUPER_ADMIN',
  PLATFORM_SUPPORT_ADMIN: 'PLATFORM_SUPPORT_ADMIN',
  CLIENT_OWNER: 'CLIENT_OWNER',
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  BRAND_MANAGER: 'BRAND_MANAGER',
  LOCATION_MANAGER: 'LOCATION_MANAGER',
  ANALYST: 'ANALYST',
  VIEWER: 'VIEWER',
} as const;

export type RoleType = typeof Role[keyof typeof Role];

export const ScopeMode = {
  ALL: 'ALL',
  RESTRICTED: 'RESTRICTED',
} as const;

export type ScopeModeType = typeof ScopeMode[keyof typeof ScopeMode];

export const Action = {
  TENANT_VIEW: 'tenant:view',
  TENANT_UPDATE: 'tenant:update',
  TENANT_DELETE: 'tenant:delete',
  BRAND_VIEW: 'brand:view',
  BRAND_CREATE: 'brand:create',
  BRAND_UPDATE: 'brand:update',
  BRAND_ARCHIVE: 'brand:archive',
  LOCATION_VIEW: 'location:view',
  LOCATION_CREATE: 'location:create',
  LOCATION_UPDATE: 'location:update',
  LOCATION_CLOSE: 'location:close',
  USER_INVITE: 'user:invite',
  USER_REMOVE: 'user:remove',
  USER_ASSIGN_ROLE: 'user:assign_role',
  INTEGRATION_CONNECT: 'integration:connect',
  INTEGRATION_DISCONNECT: 'integration:disconnect',
  INTEGRATION_MAP: 'integration:map',
  DASHBOARD_VIEW: 'dashboard:view',
  DASHBOARD_EXPORT: 'dashboard:export',
  GBP_WRITE: 'gbp:write',
  MICROSITE_VIEW: 'microsite:view',
  MICROSITE_CREATE: 'microsite:create',
  MICROSITE_UPDATE: 'microsite:update',
  MICROSITE_DELETE: 'microsite:delete',
  PRODUCT_VIEW: 'product:view',
  PRODUCT_CREATE: 'product:create',
  PRODUCT_UPDATE: 'product:update',
  PRODUCT_DELETE: 'product:delete',
  CATEGORY_MANAGE: 'category:manage',
  STORE_PRODUCT_MANAGE: 'store_product:manage',
  CALL_VIEW: 'call:view',
  CALL_MANAGE_NUMBERS: 'call:manage_numbers',
  CALL_EXPORT: 'call:export',
  CALL_RECORDING_VIEW: 'call:recording_view',
  OPPORTUNITY_VIEW: 'opportunity:view',
  OPPORTUNITY_MANAGE: 'opportunity:manage',
  OPPORTUNITY_DISMISS: 'opportunity:dismiss',
} as const;

export type ActionType = typeof Action[keyof typeof Action];

/**
 * Role capability mapping: defines which roles possess default capabilities.
 */
export const ROLE_CAPABILITIES: Record<RoleType, ReadonlySet<ActionType>> = {
  PLATFORM_SUPER_ADMIN: new Set(Object.values(Action)),
  PLATFORM_SUPPORT_ADMIN: new Set([
    Action.TENANT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.CALL_VIEW,
    Action.OPPORTUNITY_VIEW,
  ]),
  CLIENT_OWNER: new Set(Object.values(Action)),
  CLIENT_ADMIN: new Set([
    Action.TENANT_VIEW,
    Action.TENANT_UPDATE,
    Action.BRAND_VIEW,
    Action.BRAND_CREATE,
    Action.BRAND_UPDATE,
    Action.BRAND_ARCHIVE,
    Action.LOCATION_VIEW,
    Action.LOCATION_CREATE,
    Action.LOCATION_UPDATE,
    Action.LOCATION_CLOSE,
    Action.USER_INVITE,
    Action.USER_REMOVE,
    Action.USER_ASSIGN_ROLE,
    Action.INTEGRATION_CONNECT,
    Action.INTEGRATION_DISCONNECT,
    Action.INTEGRATION_MAP,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.GBP_WRITE,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_CREATE,
    Action.MICROSITE_UPDATE,
    Action.MICROSITE_DELETE,
    Action.PRODUCT_VIEW,
    Action.PRODUCT_CREATE,
    Action.PRODUCT_UPDATE,
    Action.PRODUCT_DELETE,
    Action.CATEGORY_MANAGE,
    Action.STORE_PRODUCT_MANAGE,
    Action.CALL_VIEW,
    Action.CALL_MANAGE_NUMBERS,
    Action.CALL_EXPORT,
    Action.CALL_RECORDING_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.OPPORTUNITY_DISMISS,
  ]),
  BRAND_MANAGER: new Set([
    Action.TENANT_VIEW,
    Action.BRAND_VIEW,
    Action.BRAND_UPDATE,
    Action.LOCATION_VIEW,
    Action.LOCATION_CREATE,
    Action.LOCATION_UPDATE,
    Action.INTEGRATION_MAP,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.GBP_WRITE,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_CREATE,
    Action.MICROSITE_UPDATE,
    Action.PRODUCT_VIEW,
    Action.PRODUCT_CREATE,
    Action.PRODUCT_UPDATE,
    Action.PRODUCT_DELETE,
    Action.CATEGORY_MANAGE,
    Action.STORE_PRODUCT_MANAGE,
    Action.CALL_VIEW,
    Action.CALL_MANAGE_NUMBERS,
    Action.CALL_EXPORT,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.OPPORTUNITY_DISMISS,
  ]),
  LOCATION_MANAGER: new Set([
    Action.TENANT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.LOCATION_UPDATE,
    Action.DASHBOARD_VIEW,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_UPDATE,
    Action.PRODUCT_VIEW,
    Action.STORE_PRODUCT_MANAGE,
    Action.CALL_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.OPPORTUNITY_DISMISS,
  ]),
  ANALYST: new Set([
    Action.TENANT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.CALL_VIEW,
    Action.CALL_EXPORT,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
  ]),
  VIEWER: new Set([
    Action.TENANT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.CALL_VIEW,
    Action.OPPORTUNITY_VIEW,
  ]),
};

export function hasActionPermission(role: RoleType, action: ActionType): boolean {
  return ROLE_CAPABILITIES[role]?.has(action) ?? false;
}

export function assertAuthorizedAction(role: RoleType, action: ActionType): void {
  if (!hasActionPermission(role, action)) {
    throw new Error(`Role ${role} is not authorized to perform action ${action}`);
  }
}

