export const Role = {
  PLATFORM_SUPER_ADMIN: 'PLATFORM_SUPER_ADMIN',
  PLATFORM_SUPPORT_ADMIN: 'PLATFORM_SUPPORT_ADMIN',
  AGENCY_OWNER: 'AGENCY_OWNER',
  AGENCY_ADMIN: 'AGENCY_ADMIN',
  AGENCY_MEMBER: 'AGENCY_MEMBER',
  CLIENT_OWNER: 'CLIENT_OWNER',
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  CLIENT_EDITOR: 'CLIENT_EDITOR',
  CLIENT_VIEWER: 'CLIENT_VIEWER',
  BRAND_MANAGER: 'BRAND_MANAGER',
  LOCATION_MANAGER: 'LOCATION_MANAGER',
  ANALYST: 'ANALYST',
  VIEWER: 'VIEWER',
} as const;

export type RoleType = typeof Role[keyof typeof Role];

export const ScopeMode = {
  ALL: 'ALL',
  RESTRICTED: 'RESTRICTED',
} as const;

export type ScopeModeType = typeof ScopeMode[keyof typeof ScopeMode];

export const Action = {
  TENANT_VIEW: 'tenant:view',
  TENANT_UPDATE: 'tenant:update',
  TENANT_DELETE: 'tenant:delete',
  CLIENT_VIEW: 'client:view',
  CLIENT_CREATE: 'client:create',
  CLIENT_UPDATE: 'client:update',
  CLIENT_ARCHIVE: 'client:archive',
  CLIENT_SUSPEND: 'client:suspend',
  WHITELABEL_VIEW: 'whitelabel:view',
  WHITELABEL_MANAGE: 'whitelabel:manage',
  PORTAL_DOMAIN_MANAGE: 'portal_domain:manage',
  ENTITLEMENT_VIEW: 'entitlement:view',
  ENTITLEMENT_MANAGE: 'entitlement:manage',
  BRAND_VIEW: 'brand:view',
  BRAND_CREATE: 'brand:create',
  BRAND_UPDATE: 'brand:update',
  BRAND_ARCHIVE: 'brand:archive',
  LOCATION_VIEW: 'location:view',
  LOCATION_CREATE: 'location:create',
  LOCATION_UPDATE: 'location:update',
  LOCATION_CLOSE: 'location:close',
  USER_INVITE: 'user:invite',
  USER_REMOVE: 'user:remove',
  USER_ASSIGN_ROLE: 'user:assign_role',
  INTEGRATION_CONNECT: 'integration:connect',
  INTEGRATION_DISCONNECT: 'integration:disconnect',
  INTEGRATION_MAP: 'integration:map',
  DASHBOARD_VIEW: 'dashboard:view',
  DASHBOARD_EXPORT: 'dashboard:export',
  GBP_WRITE: 'gbp:write',
  MICROSITE_VIEW: 'microsite:view',
  MICROSITE_CREATE: 'microsite:create',
  MICROSITE_UPDATE: 'microsite:update',
  MICROSITE_DELETE: 'microsite:delete',
  PRODUCT_VIEW: 'product:view',
  PRODUCT_CREATE: 'product:create',
  PRODUCT_UPDATE: 'product:update',
  PRODUCT_DELETE: 'product:delete',
  CATEGORY_MANAGE: 'category:manage',
  STORE_PRODUCT_MANAGE: 'store_product:manage',
  LEAD_VIEW: 'lead:view',
  LEAD_MANAGE: 'lead:manage',
  CALL_VIEW: 'call:view',
  CALL_MANAGE_NUMBERS: 'call:manage_numbers',
  CALL_EXPORT: 'call:export',
  CALL_RECORDING_VIEW: 'call:recording_view',
  OPPORTUNITY_VIEW: 'opportunity:view',
  OPPORTUNITY_MANAGE: 'opportunity:manage',
  OPPORTUNITY_DISMISS: 'opportunity:dismiss',
  CONTENT_VIEW: 'content:view',
  CONTENT_CREATE: 'content:create',
  CONTENT_EDIT: 'content:edit',
  CONTENT_REVIEW: 'content:review',
  CONTENT_PUBLISH: 'content:publish',
  CONTENT_ARCHIVE: 'content:archive',
  AI_CONTENT_GENERATE: 'ai:content_generate',
  LISTING_VIEW: 'listing:view',
  LISTING_MANAGE: 'listing:manage',
  LISTING_UPDATE: 'listing:update',
  LISTING_DUPLICATE_MANAGE: 'listing:duplicate_manage',
  REPORT_VIEW: 'report:view',
  REPORT_EXPORT: 'report:export',
  REPORT_SCHEDULE: 'report:schedule',
} as const;

export type ActionType = typeof Action[keyof typeof Action];

/**
 * Role capability mapping: defines which roles possess default capabilities.
 */
export const ROLE_CAPABILITIES: Record<RoleType, ReadonlySet<ActionType>> = {
  PLATFORM_SUPER_ADMIN: new Set(Object.values(Action)),
  PLATFORM_SUPPORT_ADMIN: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.REPORT_VIEW,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.LEAD_VIEW,
    Action.CALL_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.CONTENT_VIEW,
    Action.LISTING_VIEW,
    Action.WHITELABEL_VIEW,
    Action.ENTITLEMENT_VIEW,
  ]),
  AGENCY_OWNER: new Set(Object.values(Action)),
  AGENCY_ADMIN: new Set([
    Action.TENANT_VIEW,
    Action.TENANT_UPDATE,
    Action.CLIENT_VIEW,
    Action.CLIENT_CREATE,
    Action.CLIENT_UPDATE,
    Action.CLIENT_ARCHIVE,
    Action.CLIENT_SUSPEND,
    Action.WHITELABEL_VIEW,
    Action.WHITELABEL_MANAGE,
    Action.PORTAL_DOMAIN_MANAGE,
    Action.ENTITLEMENT_VIEW,
    Action.ENTITLEMENT_MANAGE,
    Action.BRAND_VIEW,
    Action.BRAND_CREATE,
    Action.BRAND_UPDATE,
    Action.BRAND_ARCHIVE,
    Action.LOCATION_VIEW,
    Action.LOCATION_CREATE,
    Action.LOCATION_UPDATE,
    Action.LOCATION_CLOSE,
    Action.USER_INVITE,
    Action.USER_REMOVE,
    Action.USER_ASSIGN_ROLE,
    Action.INTEGRATION_CONNECT,
    Action.INTEGRATION_DISCONNECT,
    Action.INTEGRATION_MAP,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.REPORT_VIEW,
    Action.REPORT_EXPORT,
    Action.REPORT_SCHEDULE,
    Action.GBP_WRITE,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_CREATE,
    Action.MICROSITE_UPDATE,
    Action.MICROSITE_DELETE,
    Action.PRODUCT_VIEW,
    Action.PRODUCT_CREATE,
    Action.PRODUCT_UPDATE,
    Action.PRODUCT_DELETE,
    Action.CATEGORY_MANAGE,
    Action.STORE_PRODUCT_MANAGE,
    Action.LEAD_VIEW,
    Action.LEAD_MANAGE,
    Action.CALL_VIEW,
    Action.CALL_MANAGE_NUMBERS,
    Action.CALL_EXPORT,
    Action.CALL_RECORDING_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.OPPORTUNITY_DISMISS,
    Action.CONTENT_VIEW,
    Action.CONTENT_CREATE,
    Action.CONTENT_EDIT,
    Action.CONTENT_REVIEW,
    Action.CONTENT_PUBLISH,
    Action.CONTENT_ARCHIVE,
    Action.AI_CONTENT_GENERATE,
    Action.LISTING_VIEW,
    Action.LISTING_MANAGE,
    Action.LISTING_UPDATE,
    Action.LISTING_DUPLICATE_MANAGE,
  ]),
  AGENCY_MEMBER: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.REPORT_VIEW,
    Action.REPORT_EXPORT,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.LEAD_VIEW,
    Action.CALL_VIEW,
    Action.CALL_EXPORT,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.CONTENT_VIEW,
    Action.LISTING_VIEW,
    Action.WHITELABEL_VIEW,
    Action.ENTITLEMENT_VIEW,
  ]),
  CLIENT_OWNER: new Set(Object.values(Action)),
  CLIENT_ADMIN: new Set([
    Action.TENANT_VIEW,
    Action.TENANT_UPDATE,
    Action.CLIENT_VIEW,
    Action.CLIENT_UPDATE,
    Action.WHITELABEL_VIEW,
    Action.ENTITLEMENT_VIEW,
    Action.BRAND_VIEW,
    Action.BRAND_CREATE,
    Action.BRAND_UPDATE,
    Action.BRAND_ARCHIVE,
    Action.LOCATION_VIEW,
    Action.LOCATION_CREATE,
    Action.LOCATION_UPDATE,
    Action.LOCATION_CLOSE,
    Action.USER_INVITE,
    Action.USER_REMOVE,
    Action.USER_ASSIGN_ROLE,
    Action.INTEGRATION_CONNECT,
    Action.INTEGRATION_DISCONNECT,
    Action.INTEGRATION_MAP,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.REPORT_VIEW,
    Action.REPORT_EXPORT,
    Action.REPORT_SCHEDULE,
    Action.GBP_WRITE,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_CREATE,
    Action.MICROSITE_UPDATE,
    Action.MICROSITE_DELETE,
    Action.PRODUCT_VIEW,
    Action.PRODUCT_CREATE,
    Action.PRODUCT_UPDATE,
    Action.PRODUCT_DELETE,
    Action.CATEGORY_MANAGE,
    Action.STORE_PRODUCT_MANAGE,
    Action.LEAD_VIEW,
    Action.LEAD_MANAGE,
    Action.CALL_VIEW,
    Action.CALL_MANAGE_NUMBERS,
    Action.CALL_EXPORT,
    Action.CALL_RECORDING_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.OPPORTUNITY_DISMISS,
    Action.CONTENT_VIEW,
    Action.CONTENT_CREATE,
    Action.CONTENT_EDIT,
    Action.CONTENT_REVIEW,
    Action.CONTENT_PUBLISH,
    Action.CONTENT_ARCHIVE,
    Action.AI_CONTENT_GENERATE,
    Action.LISTING_VIEW,
    Action.LISTING_MANAGE,
    Action.LISTING_UPDATE,
    Action.LISTING_DUPLICATE_MANAGE,
  ]),
  CLIENT_EDITOR: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.REPORT_VIEW,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_UPDATE,
    Action.PRODUCT_VIEW,
    Action.PRODUCT_CREATE,
    Action.PRODUCT_UPDATE,
    Action.CATEGORY_MANAGE,
    Action.STORE_PRODUCT_MANAGE,
    Action.LEAD_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.CONTENT_VIEW,
    Action.CONTENT_CREATE,
    Action.CONTENT_EDIT,
    Action.CONTENT_REVIEW,
    Action.CONTENT_PUBLISH,
    Action.AI_CONTENT_GENERATE,
    Action.LISTING_VIEW,
    Action.LISTING_UPDATE,
  ]),
  CLIENT_VIEWER: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.REPORT_VIEW,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.LEAD_VIEW,
    Action.CALL_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.CONTENT_VIEW,
    Action.LISTING_VIEW,
  ]),
  BRAND_MANAGER: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.BRAND_UPDATE,
    Action.LOCATION_VIEW,
    Action.LOCATION_CREATE,
    Action.LOCATION_UPDATE,
    Action.INTEGRATION_MAP,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.REPORT_VIEW,
    Action.REPORT_EXPORT,
    Action.REPORT_SCHEDULE,
    Action.GBP_WRITE,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_CREATE,
    Action.MICROSITE_UPDATE,
    Action.PRODUCT_VIEW,
    Action.PRODUCT_CREATE,
    Action.PRODUCT_UPDATE,
    Action.PRODUCT_DELETE,
    Action.CATEGORY_MANAGE,
    Action.STORE_PRODUCT_MANAGE,
    Action.LEAD_VIEW,
    Action.LEAD_MANAGE,
    Action.CALL_VIEW,
    Action.CALL_MANAGE_NUMBERS,
    Action.CALL_EXPORT,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.OPPORTUNITY_DISMISS,
    Action.CONTENT_VIEW,
    Action.CONTENT_CREATE,
    Action.CONTENT_EDIT,
    Action.CONTENT_REVIEW,
    Action.CONTENT_PUBLISH,
    Action.CONTENT_ARCHIVE,
    Action.AI_CONTENT_GENERATE,
    Action.LISTING_VIEW,
    Action.LISTING_MANAGE,
    Action.LISTING_UPDATE,
    Action.LISTING_DUPLICATE_MANAGE,
  ]),
  LOCATION_MANAGER: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.LOCATION_UPDATE,
    Action.DASHBOARD_VIEW,
    Action.REPORT_VIEW,
    Action.MICROSITE_VIEW,
    Action.MICROSITE_UPDATE,
    Action.PRODUCT_VIEW,
    Action.STORE_PRODUCT_MANAGE,
    Action.LEAD_VIEW,
    Action.CALL_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.OPPORTUNITY_DISMISS,
    Action.CONTENT_VIEW,
    Action.LISTING_VIEW,
    Action.LISTING_UPDATE,
  ]),
  ANALYST: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.DASHBOARD_EXPORT,
    Action.REPORT_VIEW,
    Action.REPORT_EXPORT,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.LEAD_VIEW,
    Action.CALL_VIEW,
    Action.CALL_EXPORT,
    Action.OPPORTUNITY_VIEW,
    Action.OPPORTUNITY_MANAGE,
    Action.CONTENT_VIEW,
    Action.LISTING_VIEW,
  ]),
  VIEWER: new Set([
    Action.TENANT_VIEW,
    Action.CLIENT_VIEW,
    Action.BRAND_VIEW,
    Action.LOCATION_VIEW,
    Action.DASHBOARD_VIEW,
    Action.REPORT_VIEW,
    Action.MICROSITE_VIEW,
    Action.PRODUCT_VIEW,
    Action.LEAD_VIEW,
    Action.CALL_VIEW,
    Action.OPPORTUNITY_VIEW,
    Action.CONTENT_VIEW,
    Action.LISTING_VIEW,
  ]),
};

export function hasActionPermission(role: RoleType, action: ActionType): boolean {
  return ROLE_CAPABILITIES[role]?.has(action) ?? false;
}

export function assertAuthorizedAction(role: RoleType, action: ActionType): void {
  if (!hasActionPermission(role, action)) {
    throw new Error(`Role ${role} is not authorized to perform action ${action}`);
  }
}

